# 動態資源切片強化學習環境配置檔
# env_v12 train_v3
# python scripts/train_v3.py --config config_v6_good.yaml --n_runs 1
env:
  lams:
    - 0.5
    - 0.3
    - 0.15
    - 0.03
    - 0.02
  mu:                # 放慢服务速率，产生更多积压压力
    - 0.5    # 原 0.8 → 平均服务时长 从 1.25 ↑ 到 2.0
    - 0.3    # 原 0.5 → 2.0 ↑ 3.33
    - 0.1    # 原 0.2 → 5.0 ↑ 10.0
    - 0.05   # 原 0.1 → 10.0 ↑ 20.0
    - 0.02   # 原 0.05 → 20.0 ↑ 50.0
  # ----- 動態資源切片參數 -----
  capacity: 3            # 初始伺服器槽數
  max_capacity: 6     # 允許擴充到的最大槽數
  scaling_delta: 1       # 每步最多增減的槽數
  # ---------------------------
  lambda_per_step: 0.9
  duration: 1500.0
  seed_val: 42
  reward_scheme:
    - 1
    - 2
    - 4
    - 8
    - 16
  reject_penalty_scheme:
    - -1
    - -2
    - -3
    - -5
    - -8
  queue_maxlen: 4

agent:
  policy: MlpPolicy
  learning_rate: 1e-5
  buffer_size: 1000000
  learning_starts: 1000
  batch_size: 512
  gamma: 0.99
  train_freq: 1
  target_update_interval: 4000
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  exploration_fraction: 0.6

trainer:
  total_timesteps: 500000
  log_dir: logs/
  save_freq: 10000
  save_path: dqn_service_queue